#!/bin/bash
login=$(</bin/blih.config)
if [[ $# -eq 0 ]] ; then
    printf '\033[1mNAME\033[0m
	\033[1;32mezb\033[0m - Version simplifiee de la commande blih (Easy blih)

\033[1mSYNOPSIS\033[0m
	\033[1;32mezb\033[0m \033[0;34m\033[1m[OPTIONS]...\033[0m

\033[1mDESCRIPTION\033[0m
	Raccourcis des commandes blih
	Voici la liste des options :
	\033[0;34m\033[1mupload\033[0m\033[0m
		Envoie la clef SSH generee dans le dossier par defaut
	\033[0;34m\033[1mcreate\033[0m\033[0m=\033[1;35mNOM_DU_DEPOT\033[0m 
		Cree un nouveau repository dont le \033[1;35mNOM_DU_DEPOT\033[0m est donne en argument
	\033[0;34m\033[1msetacl\033[0m\033[0m=\033[1;35mNOM_DU_DEPOT USER DROITS\033[0m
		Octroie les \033[1;35mDROTIS\033[0m du \033[1;35mNOM_DU_DEPOT\033[0m au \033[1;35mUSER\033[0m
	\033[0;34m\033[1mgetacl\033[0m\033[0m=\033[1;35mNOM_DU_DEPOT\033[0m
		Permet de lire les droits octroyes au \033[1;35mNOM_DU_DEPOT\033[0m
	\033[0;34m\033[1mdelete\033[0m\033[0m=\033[1;35mNOM_DU_DEPOT\033[0m
		Supprime le repository dont le \033[1;35mNOM_DU_DEPOT\033[0m est donne en argument
	\033[0;34m\033[1mlist\033[0m\033[0m
		Liste tout vos repository
	\033[0;34m\033[1mclone\033[0m\033[0m=\033[1;35mNOM_DU_DEPOT\033[0m
		Clone le repository \033[1;35mNOM_DU_DEPOT\033[0m dans votre dossier actuel
	\033[0;34m\033[1mconfig\033[0m\033[0m=\033[1;35mLOGIN\033[0m
		Change votre \033[1;35mLOGIN\033[0m utilise lors des commandes
'
    exit 0
fi

if [ $1 = 'upload' ]; then
	blih -u $login sshkey upload
elif [ $1 = 'create' ]; then
	blih -u $login repository create $2
elif [ $1 = 'setacl' ]; then
	blih -u $login repository setacl $2 $3 $4
elif [ $1 = 'getacl' ]; then
	blih -u $login repository getacl $2
elif [ $1 = 'delete' ]; then
	blih -u $login repository delete $2
elif [ $1 = 'list' ]; then
	blih -u $login repository list
elif [ $1 = 'clone' ]; then
	git clone git@git.epitech.eu:/chiocc_b/$2
elif [ $1 = 'config' ]; then
	echo $2 > '/bin/blih.config'
elif [ $1 = 'login' ]; then
	echo $login
elif [ $1 = 'help' ]; then
	printf '\033[1mNAME\033[0m
	\033[1;32mezb\033[0m - Version simplifiee de la commande blih (Easy blih)

\033[1mSYNOPSIS\033[0m
	\033[1;32mezb\033[0m \033[0;34m\033[1m[OPTIONS]...\033[0m

\033[1mDESCRIPTION\033[0m
	Raccourcis des commandes blih
	Voici la liste des options :
	\033[0;34m\033[1mupload\033[0m\033[0m
		Envoie la clef SSH generee dans le dossier par defaut
	\033[0;34m\033[1mcreate\033[0m\033[0m=\033[1;35mNOM_DU_DEPOT\033[0m 
		Cree un nouveau repository dont le \033[1;35mNOM_DU_DEPOT\033[0m est donne en argument
	\033[0;34m\033[1msetacl\033[0m\033[0m=\033[1;35mNOM_DU_DEPOT USER DROITS\033[0m
		Octroie les \033[1;35mDROTIS\033[0m du \033[1;35mNOM_DU_DEPOT\033[0m au \033[1;35mUSER\033[0m
	\033[0;34m\033[1mgetacl\033[0m\033[0m=\033[1;35mNOM_DU_DEPOT\033[0m
		Permet de lire les droits octroyes au \033[1;35mNOM_DU_DEPOT\033[0m
	\033[0;34m\033[1mdelete\033[0m\033[0m=\033[1;35mNOM_DU_DEPOT\033[0m
		Supprime le repository dont le \033[1;35mNOM_DU_DEPOT\033[0m est donne en argument
	\033[0;34m\033[1mlist\033[0m\033[0m
		Liste tout vos repository
	\033[0;34m\033[1mclone\033[0m\033[0m=\033[1;35mNOM_DU_DEPOT\033[0m
		Clone le repository \033[1;35mNOM_DU_DEPOT\033[0m dans votre dossier actuel
	\033[0;34m\033[1mconfig\033[0m\033[0m=\033[1;35mLOGIN\033[0m
		Change votre \033[1;35mLOGIN\033[0m utilise lors des commandes
'
else
	blih -u $login $@
fi